### ISSUE TITLE
Config updates keep hanging

### ISSUE THREAD

**Issue by koburg** [hassio-addons/addon-zwavejs2mqtt#156]
after new version 0.14 

I get the config updates keep telling me there is an update and after pressing update it still appear tried 
to restart HASS ect. no luck

<img width="499" alt="6FA63267-60FB-4557-898E-F5D3A23B959D" src="https://user-images.githubusercontent.com/3473374/116808310-6a9b1a00-ab38-11eb-8954-3183c1982a9c.png">

![69DDAD4D-538C-4AA5-A7D4-C2F177F7645C_4_5005_c](https://user-images.githubusercontent.com/3473374/116808337-8bfc0600-ab38-11eb-9a43-799a57dd68a8.jpeg)

**Comment by yuvalmesika** [comment]
Same issue here.

more details from the log addon logs:
DRIVER   Config update failed: Package manager exited with code 1
               Error loading root package.json and package-lock.json: This directory tree does not contain a directory with package.json and a lockfile!
INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }

**Comment by Myztillx** [comment]
I am still seeing this issue after updating to version 0.14.1.

I see this in the logs:
```
INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }
```

I have cleared cache and restarted Home Assistant OS with no luck...

**Comment by peng1can** [comment]
Still seeing the same thing as Myztillx after upgrading.

**Comment by w0lf3h** [comment]
Same after update to 0.14.1 as well.

**Comment by yuvalmesika** [comment]
same thing on 0.14.1
log file: 
INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
DRIVER   Config update failed: Package manager exited with code undefined
INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }

**Comment by deku-m** [comment]
Same at my configuration aswell (0.14.1):
2021-05-04 20:26:32.579 INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
2021-05-04 20:26:33.197 INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }

**Comment by koburg** [comment]
same here also 0.14.1

**Comment by trentjw** [comment]
New zwave-js config version available: 7.3.1-20210503

**Comment by TheDK** [comment]
Also still seeing this:
```
2021-05-11 15:30:08.836 INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
2021-05-11 15:30:10.039 INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }
```
HA and Add-on latest versions.

**Comment by koburg** [comment]
Dont know why this issue is been closed so fast when it is NOT solved yet.

**Comment by quadhammer** [comment]
> Dont know why this issue is been closed so fast when it is NOT solved yet.

Yup, still broken for me
 Z-Wave JS to MQTT
 Current version: 0.14.1 

core-2021.5.2

**Comment by peterbaker** [comment]
Same. Fresh install, have only ever been on 0.14.1

"New zwave-js config version available: 7.3.1-20210503"

Clicking install shows a "Successfully call api installConfigUpdate" dialog, but nothing happens and the config notification remains.

**Comment by quadhammer** [comment]
Z-Wave JS to MQTT
Current version: 0.15.0 
has fixed this for me

**Comment by yaggermr** [comment]
Same Fixed! Awesome!

**Comment by koburg** [comment]
Yes Also fixed here   👍🏻

**Comment by trentjw** [comment]
this issue is back 

New zwave-js config version available: 7.7.2-20210602.

Mind that some changes may require a re-interview of affected devices

**Comment by quadhammer** [comment]
Same here.  Clicking install does nothing.

**Comment by kickouille** [comment]
Also having the same problem while running latest docker image:

```
INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }
```

Seeing a lot of activity with this command:

`node /opt/yarn-v1.22.5/bin/yarn.js install --production`

I had to increase disk space space and swap on a Raspberry for it not to crash.

Also noticed that no `store/.config-db` folder is created, does that happen only if the process is successful?

Regards,

Yanik

**Comment by koburg** [comment]
Same here it is back again hanging Update

**Comment by trentjw** [comment]
Same issue with a venv install
